spring:
  datasource:
    #数据库链接驱动
    driver-class-name: com.mysql.jdbc.Driver
    #数据库名
    name: test
    #url
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #用户名
    username: root
    #密码
    password: 123456

mybatis:
  #配置映射文件
  mapper-locations: classpath:mapper/*.xml
  #配置实体类
  type-aliases-package: com.ray.demo.entity